import '~/styles/globals.css'

import { GeistSans } from 'geist/font/sans'
import { type Metadata } from 'next'

import { TRPCReactProvider } from '~/trpc/react'

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default async function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    // TODO: add auth later
    // const session = await auth()
    // if (!session?.user) {
    //     return redirect('/api/auth/signin')
    // }

    return (
        <html lang='en' className={`${GeistSans.variable}`}>
            <body>
                <TRPCReactProvider>{children}</TRPCReactProvider>
            </body>
        </html>
    )
}
